name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Клонировать репозиторий
      uses: actions/checkout@v4

    - name: Установить Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'   # здесь укажи свою версию Go, если нужна другая

    - name: Проверить зависимости
      run: go mod tidy

   - name: Собрать проект
      run: go build ./...

    - name: Прогнать тесты
      run: go test ./...
